GoXue/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from front_page import urls
from mi_user import urls
from mi_class import urls
from django.views.static import serve
from GoXue.settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('front_page.urls')),
    path('user/', include('mi_user.urls')),
    path('class/',include('mi_class.urls')),
    re_path(r'wenjian/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
    path('search/', include('haystack.urls')),  # 全文检索路由
    ]

front_page/urls.py
from django.urls import path
from . import views
app_name = 'front_page'

urlpatterns = [
    path('', views.mi_index, name='front_index'),
]

mi_class/urls.py
from django.urls import path,re_path
from . import views


app_name = 'mi_class'
urlpatterns = [
    path('classUpload/', views.user_class_upload, name='user_class_upload'),
    path('classUpload/<int:class_id>/', views.user_class_upload_id, name='user_class_upload_id'),
    path('class/damin/',views.class_admin,name='class_admin'),
    path('lesson/admin/',views.lesson_admin,name='lesson_admin'),
    path('class/<str:sign>/', views.user_class, name='user_class'),
    path('video/<int:class_id>/', views.video_play, name='video_play_id'),
    path('video/switch/', views.switch_play, name='video_play_switch'),
    path('lesson/comment/', views.comment, name='class_comment'),
    # path('lesson/download/', views.download, name='class_download'),
    path('lesson/dataadmin/', views.admin_data, name='data_admin'),
]

mi_user/urls.py
from django.urls import path,re_path
from . import views

app_name = 'mi_user'
urlpatterns = [
    path('login/', views.mi_login, name='login'),
    path('register/', views.mi_register, name='register'),
    path('logout/', views.mi_logout, name='logout'),
    path('forgetpw/', views.reset_pw, name='resetpw'),
    path('information/', views.user_information, name='user_information'),
    path('information/update/',views.update_information,name='update_information'),
    path('information/updatepassword/',views.update_password,name='updatepassword'),
    path('imgUpdate/',views.img_update,name='imgupdate'),
]

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GO学-首页</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="/static/front_page/css/index.css">
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <link rel="shortcut icon" href="\GoXue\wenjian\img\favicon.ico">
</head>
<body>
<div class="header">
    <img style="display:inline-block;width: 50px;height: 50px;margin-top: 3px" class="header_left" src="\GoXue\wenjian\img\网站logo.png">
    <span class="header_right">
                {% if request.user.is_authenticated %}
                    <span class="header_span"><a href="{% url  'mi_class:user_class' sign='all' %}">我的课程</a></span>
                    <span class="header_span user_information">
                        <img style="width: 40px;height: 40px;border-radius: 50%" src={{ request.user.userotherinformtion.headImg.url  }}>
                        <a  href="{% url 'mi_user:user_information' %}" >{{ request.user.username }}</a>
                        <ul class="infomation_slect">
                            <li><a style="display: block" href="{% url 'mi_user:user_information' %}">个人中心</a></li>
                            <li><a style="display: block" href="{% url 'mi_user:logout' %}">退出登陆</a></li>
                        </ul>
                    </span>
                {% else %}
                    <span style="display: inline-block;margin-left: 10px"><a href="{% url 'mi_user:login' %}">登陆</a></span>
                    <span style="display: inline-block;margin-left: 10px"><a href="{% url 'mi_user:register' %}">注册</a></span>
                {% endif %}
    </span>
    <div class="search_div">
       <form action="{% url 'haystack_search' %}" method="get">
           {% csrf_token %}
           <input type="text" placeholder="课程名/作者搜索课程" class="search_input" name="q"/>
           <button type="submit" class="search_btn">搜索</button>
       </form>
    </div>

</div>
<div class="content">
    <h2 class="index_title">推荐课程</h2>
    {% for i in page.object_list %}
        <div class="class_item">
            <a href="{% url 'mi_class:video_play_id' class_id=i.id %}">
            <img class="class_picture" src="{{ i.class_image.url }}" alt="课程封面" width="220px" height="220px"/></a>
            <spean class="class_title">{{ i.title }}</spean>
            <spean class="class_author">{{ i.author }}</spean>
        </div>
    {% endfor %}
    <div class="page_div">
        <ul class="pagination">
            {# 如果当前页还有上一页 #}
            {% if page.has_previous %}
                <li>
                    {# 点击a标签，跳转到上一页链接 ?index  为地址后面拼接的参数 #}
                    <a href="?index={{ page.previous_page_number }}">上一页</a>
                </li>
            {% else %}
                {# 如果没有上一页， 则上一页按钮不可点击 #}
                <li class="disabled">
                    <a href="#">上一页</a>
                </li>
            {% endif %}

            {% for page_number in paginator.page_range %}
                {# 获取当前页的页码 #}
                {% if page_number == page.number %}
                    {# 如果是当前页的话，选中 #}
                    <li class="active">
                        <a href="?index={{ page_number }}">{{ page_number }}</a>
                    </li>
                {% elif page_number == 1%}
                    <li>
                        <a href="?index={{ page_number }}">{{ page_number }} </a>
                    </li>
                {% elif page_number == page.number|add:3  or page_number == page.number|add:-3%}
                    <li>
                        <a href="#">...</a>
                    </li>
                {% elif page_number <= page.number|add:2  and page_number >= page.number|add:-2%}
                    <li>
                        <a href="?index={{ page_number }}">{{ page_number }}</a>
                    </li>
                {% elif page_number == paginator.num_pages %}
                <li>
                    <a href="?index={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}

            {% endfor %}
            {% if page.has_next %}
                <li>
                    <a href="?index={{ page.next_page_number }}">下一页</a>
                </li>
            {% else %}
                <li class="disabled">
                    <a href="#">下一页</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>
<div class="footer">软件1731-肖沵鑫的毕业设计<br/>
    171414337
</div>

</body>
</html>

templates/information.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人信息</title>
    <link rel="stylesheet" href="/static/front_page/css/information.css">
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <link rel="shortcut icon" href="\GoXue\wenjian\img\favicon.ico">
</head>
<body>
<div class="header">
        <ul class="header_ul">
            <li class="header_li"><a href="{% url 'front_page:front_index' %}">首页</a></li>
{#            <li class="header_li"><a href="{% url 'mi_user:user_information' %}">个人中心</a></li>#}
        </ul>
</div>
<div class="outside_div">
    <h2 style="text-align: center;color:#31b0d5;padding-top: 20px;">
        个人信息
    </h2>
    <h3 class="title">头像</h3>
    <span class="title_cont"> <img style="width: 80px;height:80px;border-radius: 50%" src={{ user.userotherinformtion.headImg.url }} /></span>
    <h3 class="title">用户名</h3>
    <span class="title_cont"> {{ user.username }}</span>
    <h3 class="title">登陆手机</h3>
    <span class="title_cont">{{ user.telephone }}</span>
    <h3 class="title">邮箱</h3>
    {% if user.email is None %}
        <span class="title_cont">暂未绑定邮箱</span>
    {% else %}
        <span class="title_cont">{{ user.email }}</span>
    {% endif %}
    <div class="button_div">
        <button class="update">修改信息</button>
        <button class="update_word">修改密码</button>
        <button class="update_img">修改头像</button>
    </div>
</div>
<div class="update_div" style="hidden:hidden">
    <form method="post" action="{% url 'mi_user:update_information' %}">
        {% csrf_token %}
        <label class="update_laber">用户名:</label>
        <input name="username" class="form_input"/><br/>
        <label class="update_laber">邮箱</label>
        <input name="email" class="form_input"/><br/>
        <div class="img_btn_div">
            <button class="update_commit" type="submit">确认修改</button>
            <button class="update_cancle" type="reset">取消修改</button>
        </div>
    </form>
</div>
<div class="update_password" style="hidden:hidden">
    <form method="post" action="{% url 'mi_user:updatepassword' %}">
        {% csrf_token %}
        <label class="update_laber">旧密码</label>
        <input name="old_password" class="form_input" type="password"/><br/>
        <label class="new_password">新密码</label>
        <input name="new_password" class="form_input" type="password"/><br/>
        <div class="img_btn_div">
            <button class="update_commit" type="submit">确认修改</button>
            <button class="update_cancle" type="reset">取消修改</button>
        </div>
    </form>
</div>
<form class="uptateImg" method="post" action="{% url 'mi_user:imgupdate' %} " enctype="multipart/form-data">
{#        {% csrf_token %}#}
    <label class="title_img">上传新的头像</label>
    <input type="file" name="imgflie" class="title_img"/>
    <div class="img_btn_div">
        <button type="button" class="img_commit" data-id={{ lesson.id }}>确认上传</button>
        <button type="reset" class="imgreset">取消上传</button>
    </div>
</form>
<div class="footer">软件1731-肖沵鑫的毕业设计<br/>
    171414337
</div>
<script>
    $(document).ready(function () {
        $('.update').on('click', function () {
            $('.update_div').css('display', 'block');
        });
        $('.update_word').on('click', function () {
            $('.update_password').css('display', 'block');
        });

        $('.update_commit').on('click', function () {
            $('.update_div').css('display', 'none');
            $('.update_password').css('display', 'none');
        });
        $('.update_cancle').on('click', function () {
            $('.update_div').css('display', 'none');
            $('.update_password').css('display', 'none');
        });
        $('.update_img').on('click', function () {
               $('.uptateImg').css('display','block')
        });
         $('.imgreset').on('click', function () {
               $('.uptateImg').css('display','none')
        });
          $('.img_commit').on('click', function () {
            var formData= new FormData();
            var img = $("input[name='imgflie']").val()
            if(img == ''){
                alert('请上传文件')
                return false;
            };
            formData.append("sign",'header_img');
            formData.append("csrfmiddlewaretoken",'{{ csrf_token }}');
            formData.append('img',$("input[name='imgflie']")[0].files[0]);
            $.ajax({
                type : "post",
                url : "/user/imgUpdate/",
                data : formData,
                processData : false,
                contentType : false,
                success : function(res){
                    if(res.code ==1){
                        alert("头像修改成功!");
                        window.location.reload()
                    };
                    if(res.code ==0){
                          alert(res.error);
                           window.location.reload()
                    };
                }
            });
        });
    })
</script>
</body>
</html>

templates/play.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>课程详情页面</title>
        <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <link rel="stylesheet" href="/static/front_page/css/play.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
{#    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>#}
    <script type="text/javascript" src="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="shortcut icon" href="\GoXue\wenjian\img\favicon.ico">
</head>
<body>
<div class="heade_play">
    <ul class="header_ul">
        <li class="header_li"><a href="{% url 'front_page:front_index' %}">首页</a></li>
        {% if request.user.is_authenticated %}
            <li class="header_li"><a href="{% url 'mi_user:user_information' %}">个人中心</a></li>
        {% endif %}
    </ul>
</div>
<div id="play_div">
    <div class="play_div">
        <video id="play" controls="controls" width="980px" height="520px">
            <source class="play_class" src="{{ MEDIA_URL }}{{ chapter_lists.0.video_objects.first.file }}"
                    type="audio/ogg">
        </video>
    </div>
    <div class="details">
        <h2 class="heading">{{ lesson.title }}</h2>
        <span class="heading">{{ lesson.author }}</span>
        <h4 class="heading" style="color: black; margin-block-start: 0.3em;">课程简介</h4>
        <span class="heading" style="margin-left: 20px">{{ lesson.introduce }}</span>
    </div>
    <ul class="nav nav-tabs">
        <li class="active"><a href="#catalog" data-toggle="tab">目录</a></li>
        <li ><a href="#data" data-toggle="tab">资料</a></li>
        <li ><a href="#comment" data-toggle="tab">评论</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="catalog">
            <table class="leasson_table">
                {% if chapter_lists %}
                    {% for i in chapter_lists %}
                        <tr style="display: block;margin-top: 10px">
                            <th style="float: left">第{{ forloop.counter }}章：{{ i.chapter_object.name }}</th>
                        </tr>
                        {% for j in i.video_objects %}
                            <tr class={{ j.id }}>
                                <td>
                                    <button class="switch" data-id="{{ j.id }}" type="button">{{ j.file_name }}</button>
                                </td>
                            </tr>
                        {% endfor %}
                    {% endfor %}
                {% else %}
                    <span style="display:block;text-align: center;margin-top: 10px;color: #4cae4c">作者比较懒，没有上传视频哦！</span>
                {% endif %}
            </table>
        </div>

        <div class="tab-pane " id="data">
            <table class="leasson_table">
                {% if data_list %}
                    {% for i in data_list %}
                        <tr style="display: block;margin-top: 10px">
                            <th style="float: left"><a href={{ i.file.url }}>{{ i.name }}</a></th>
                        </tr>
                    {% endfor %}
                {% else %}
                    <span style="display:block;text-align: center;margin-top: 10px;color: #4cae4c"> 作者比较懒，没有上传资料哦！</span>
                {% endif %}
            </table>
        </div>

        <div class="tab-pane " id="comment">
            <form action="{% url 'mi_class:class_comment' %}" method="post" class="comment_form">
                <textarea rows="5" name="comment" placeholder="写下你的想法" class="commtent_context"></textarea>
                <button type="button" class="comment_button" data-id={{ lesson.id }}>确认评论</button>
            </form>
            <div class="comment_content">
                {% for i in page.object_list %}
                    <li class="class_item">
                        <div class="userImg" ><img style="width: 68px;height: 68px;border-radius: 50%" src={{ i.user.userotherinformtion.headImg.url }} /></div>
                        <div class="userInfon">
                                <span style="color: #31b0d5">{{ i.user.username }}</span>
                                <span>{{ i.content }}</span>
                                <span style="color: #bbb;margin-top: 10px">{{ i.data }}</span>
                        </div>
                    </li>
                {% endfor %}
                <div class="page_div">
                    <ul class="pagination">
                        {# 如果当前页还有上一页 #}
                        {% if page.has_previous %}
                            <li>
                                {# 点击a标签，跳转到上一页链接 ?index  为地址后面拼接的参数 #}
                                <a href="?index={{ page.previous_page_number }}">上一页</a>
                            </li>
                        {% else %}
                            {# 如果没有上一页， 则上一页按钮不可点击 #}
                            <li class="disabled">
                                <a href="#">上一页</a>
                            </li>
                        {% endif %}

                        {% for page_number in paginator.page_range %}
                            {# 获取当前页的页码 #}
                            {% if page_number == page.number %}
                                {# 如果是当前页的话，选中 #}
                                <li class="active">
                                    <a href="?index={{ page_number }}">{{ page_number }}</a>
                                </li>
                            {% elif page_number == 1 %}
                                <li>
                                    <a href="?index={{ page_number }}">{{ page_number }} </a>
                                </li>
                            {% elif page_number == page.number|add:3  or page_number == page.number|add:-3 %}
                                <li>
                                    <a href="#">...</a>
                                </li>
                            {% elif page_number <= page.number|add:2  and page_number >= page.number|add:-2 %}
                                <li>
                                    <a href="?index={{ page_number }}">{{ page_number }}</a>
                                </li>
                            {% elif page_number == paginator.num_pages %}
                                <li>
                                    <a href="?index={{ page_number }}">{{ page_number }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if page.has_next %}
                            <li>
                                <a href="?index={{ page.next_page_number }}">下一页</a>
                            </li>
                        {% else %}
                            <li class="disabled">
                                <a href="#">下一页</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="footer">软件1731-肖沵鑫的毕业设计<br/>
    171414337
</div>
<script>
    $(document).ready(function () {
        $(".switch").click(function () {
            var play_id = $(this).data("id");
            $.ajax({
                url: "/class/video/switch/",
                type: "POST",
                dataType: "json",
                async: false,
                data: {
                    'play_id': play_id,
                    'sign': 'switch',  //修改信息
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                success: function (res) {
                    $('#play').remove()
                    $('.play_div').append(' <video id="play"  controls="controls" width="870px" height="520px"><source class="play_class" src=res.play_src type="audio/ogg"></video>')
                    var class_object = $('.play_class');
                    class_object.attr('src', res.play_src)
                }, error: function () {
                    alert('失败了')
                }
            })
        });
        $(".comment_button").on('click', function () {
            var lesson_id = $(this).data("id");
            var comment = $("textarea[name='comment']").val()
            $.ajax({
                url: '/class/lesson/comment/',
                type: "POST",
                dataType: "json",
                async: false,
                data: {
                    'lesson_id': lesson_id,
                    'comment': comment,
                    'sign': 'comment',
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                }, success: function (res) {
                    $('.comment_content').prepend(
                        '<li class="class_item">' +
                            '<div class="userImg" ><img style="width: 68px;height: 68px;border-radius: 50%" '+ 'src=' + res.headImgUrl +'/>' + '</div>' +
                            '<div class="userInfon"><span style="color: #31b0d5">'+  res.user_name  + '</span><span>'+  res.comment  + '</span><span style="color: #bbb;margin-top: 10px">'+ res.data  + '</span></div>' +
                        '</li>')
                }, error: function (res) {
                    alert('评论失败啦，记得登陆才可以评论哦')
                }
            })
        });
    });
</script>

</body>

</html>

templates/user_class.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的课程</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="/static/front_page/css/my_class.css">
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <link rel="shortcut icon" href="\GoXue\wenjian\img\favicon.ico">
</head>
<body>
<div class="header">
    <img style="display:inline-block;width: 50px;height: 50px;margin-top: 3px" class="header_left" src="\GoXue\wenjian\img\网站logo.png">
    <span class="header_left"><a href="{% url 'front_page:front_index' %}">首页</a></span>
    <span class="header_right">
                <span class="header_span"><a href="{% url 'mi_class:user_class_upload' %}">上传课程</a></span>
                 <span class="header_span"><a
                         href="{% url 'mi_user:user_information' %}">{{ request.user.username }}</a></span>
            </span>
</div>
<div class="content">
    <div class="content-left">
        <ul class="left_ul">
            <li class="left_li" data-sign="all"><a href="{% url 'mi_class:user_class' sign='all' %}">所有课程</a></li>
            <li class="left_li" data-sign="yes"><a href="{% url 'mi_class:user_class' sign='yes' %}">已发布课程</a></li>
            <li class="left_li" data-sign="not"><a href="{% url 'mi_class:user_class' sign='no' %}">未发布课程</a></li>
        </ul>
    </div>
    {% if not page.object_list %}
    <div class="content-right">
            <span style="display: inline-block;color:#000000;margin-left: 410px;margin-top: 30px;font-size: 16px">暂无课程</span>
    </div>
    {% else %}
    <div class="content-right">
        {% for i in page.object_list %}
            <ul class="right_ul">
             <img src="{{ MEDIA_URL }}{{ i.class_image }}" style="display:inline-block;width: 160px;height:160px;margin-right:30px;float: left">
                <li class="right_li" style="display: inline-block">
                    <div style="display: inline-block;">
                        <a style="font-size:28px;display:block;margin-top: 3px" href={% url 'mi_class:user_class_upload_id' class_id=i.id %} >{{ i.title }}</a>
                        {% if i.is_release == 1 %}
                            <span style="display: block;margin-right: 20px;margin-top: 3px">已发布</span>
                        {% else %}
                            <span style="display: block;margin-right: 20px;margin-top: 3px">未发布</span>
                        {% endif %}
                        <span>{{ i.author }}</span>
                        <span style="display: block;margin-top: 3px">{{ i.create_data }}</span>
                        <div class="btn_div">
                            {% if i.is_release != 1 %}
                                <button type="button" class="btn release" style="background-color: #4cae4c;color: white" data-id={{ i.id }} >发布</button>
                            {% endif %}
                            <button type="button" class="btn del" data-id={{ i.id }} data-sign='del'>删除</button>
                        </div>
                    </div>
                </li>
            </ul>
        {% endfor %}
    </div>
        <div class="page_div">
            <ul class="pagination">
                {# 如果当前页还有上一页 #}
                {% if page.has_previous %}
                    <li>
                        {# 点击a标签，跳转到上一页链接 ?index  为地址后面拼接的参数 #}
                        <a href="?index={{ page.previous_page_number }}">上一页</a>
                    </li>
                {% else %}
                    {# 如果没有上一页， 则上一页按钮不可点击 #}
                    <li class="disabled">
                        <a href="#">上一页</a>
                    </li>
                {% endif %}
                {% for page_number in paginator.page_range %}
                    {# 获取当前页的页码 #}
                    {% if page_number == page.number %}
                        {# 如果是当前页的话，选中 #}
                        <li class="active">
                            <a href="?index={{ page_number }}">{{ page_number }}</a>
                        </li>
                    {% elif page_number == 1%}
                    <li>
                        <a href="?index={{ page_number }}">{{ page_number }} </a>
                    </li>
                {% elif page_number == page.number|add:3  or page_number == page.number|add:-3%}
                    <li>
                        <a href="#">...</a>
                    </li>
                {% elif page_number <= page.number|add:2  and page_number >= page.number|add:-2%}
                    <li>
                        <a href="?index={{ page_number }}">{{ page_number }}</a>
                    </li>
                {% elif page_number == paginator.num_pages %}
                <li>
                    <a href="?index={{ page_number }}">{{ page_number }}</a>
                </li>
                    {% endif %}
                {% endfor %}
                {% if page.has_next %}
                    <li>
                        <a href="?index={{ page.next_page_number }}">下一页</a>
                    </li>
                {% else %}
                    <li class="disabled">
                        <a href="#">下一页</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
</div>
<script>
    $(document).ready(function(){
        $('.release').on('click',function(){
            var id = $(this).data("id");
            $.ajax({
                url: "/class/lesson/admin/",
                type: "POST",
                dataType: "json",
                async: false,
                data: {
                    'id': id,
                    'sign':'release',
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                success: function(res){
                    if (res.code ==1){
                         alert('发布成功')
                            window.location.reload()
                    }
                },error(res){
                      if (res.code ==0){
                         alert('发布失败')
                        window.location.reload()
                    }
                }
            })
        });
        $('.del').on('click',function(){
            var id = $(this).data("id");
            $.ajax({
                url: "/class/lesson/admin/",
                type: "POST",
                dataType: "json",
                async: false,
                data: {
                    'id': id,
                    'sign':'del',
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                success: function(res){
                    if (res.code ==1){
                         alert('删除成功')
                            window.location.reload()
                    }
                },error(res){
                      if (res.code ==0){
                         alert('删除成功')
                        window.location.reload()
                    }
                }
            })
        });
    })
</script>
</body>
</html>

templates/user_class_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="UTF-8">
    <title>我的课程</title>
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <link rel="stylesheet" href="/static/front_page/css/upload_class.css">
    <link rel="shortcut icon" href="\GoXue\wenjian\img\favicon.ico">
</head>
<body>
<div class="father_div">
    <div class="header">
        <ul class="header_ul">
            <li class="header_li"><a href="{% url 'front_page:front_index' %}">首页</a></li>
            <li class="header_li"><a href="{% url  'mi_class:user_class' sign='all' %}">我的课程</a></li>
            <li class="header_li"><a href="{% url 'mi_user:user_information' %}">个人中心</a></li>
        </ul>
    </div>
</div>
<div class="upload_div">
    <h2 style="text-align: center;color:#31b0d5;padding-top: 20px;margin-block-start: 0;margin-block-end:0;">开设你的新课程吧</h2>

    <form class="form_div"  method="post" enctype="multipart/form-data" multiple=True>
    {% csrf_token %}
     <laber class="title">课程名</laber>{% if code == 1 %}<span style="color: red">{{ errors.title}}</span>{% endif %}
    <input type="text" name="title" placeholder="请输入课程名字" id="title" class="form_input" />
      <laber class="title">作者</laber>
    <input type="text" name="author" placeholder="请输入作者" class="form_input"/>
          <laber class="title">课程简介</laber>{% if code == 1 %}<span style="color: red">{{ errors.introduce}}</span>{% endif %}
      <textarea cols="20" rows="20" name="introduce" placeholder="请描述下课程简介" class="form_input"></textarea>
    <label class="title">上传课程封面(只支持上传png/jpg格式)</label><span style="color: red">{{ imgerror }}</span>
    <input name="img" type="file" placeholder="上传封面" class="form_input">
    <label class="title">章节</label>
        <button type='button' class="btn_add">添加章节</button>
    <div class="video_upload">
        <label class="title">章节名称</label>
        <input class="chapter_input form_input" name="chapter_name" placeholder="请输入章节的名称" />
        <label class="title">上传相关文件</label>
        <input type="file" name="myfile" multiple=True placeholder="上传视频" class="form_input"/>
        <div class="btn_video">
            <button type="submit" class="commit_add">确认上传</button>
            <button type="button" class="cancle_add">取消上传</button>
        </div>
    </div>
    <div class="btn_div">
        <button type="submit"  class="btn_cmmit">确认上传</button>
        <button type="reset"  class="btn_cancle">取消上传</button>
    </div>

</form>
</div>
<div class="footer">软件1731-肖沵鑫的毕业设计<br/>
        171414337
    </div>
{#<div class="box">#}
{##}
{#</div>#}
<script>
    $(document).ready(function(){
        $('.btn_add').on('click',function(){
            var  title = $('input[name="title"]').val()
            var  introduce = $('textarea[name="introduce"]').val()
            if(!title ||!introduce){
                alert('请先填写课程名和课程简介哈！')
            }else {
                $('.btn_add').on('click',function(){
                $('.box').css('display', 'block');
                $('.video_upload').css('display', 'block');
                });
                 $('.cancle_add').on('click',function(){
                $('.box').css('display', 'none');
                $('.video_upload').css('display', 'none');
                });
            }
        });
    })
</script>
</body>
</html>